import Head from "next/head";
import Image from "next/image";
import homeClass from "../styles/Home.module.scss";
import layoutClass from "../components/layout/layout.module.scss";
export default function Home() {
  return (
    <div className={homeClass.container}>
      <Head>
        <title>Hotel View</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={homeClass.gallery}>
        <figure className={homeClass["gallery__item"]}>
          <Image
            className={homeClass["gallery__photo"]}
            layout="fill"
            objectFit="contain"
            src="/img/hotel-1.jpg"
            alt="User Photo"
          ></Image>
        </figure>
        <figure className={homeClass["gallery__item"]}>
          <Image
            className={homeClass["gallery__photo"]}
            layout="fill"
            objectFit="contain"
            src="/img/hotel-2.jpg"
            alt="User Photo"
          ></Image>
        </figure>
        <figure className={homeClass["gallery__item"]}>
          <Image
            className={homeClass["gallery__photo"]}
            layout="fill"
            objectFit="contain"
            src="/img/hotel-3.jpg"
            alt="User Photo"
          ></Image>
        </figure>
      </div>

      <div className={homeClass.overview}>
        <h1 className={homeClass["overview__heading"]}>Hotel Las Palmas</h1>
        <div className={homeClass["overview__stars"]}>
          {Array.from(Array(5), (e, i) => {
            return (
              <svg className={homeClass["overview__icon-star"]}>
                <use xlinkHref="/img/sprite.svg#icon-star"></use>
              </svg>
            );
          })}
        </div>
        <div className={homeClass["overview__location"]}>
          <svg className={homeClass["overview__icon-location"]}>
            <use xlinkHref="/img/sprite.svg#icon-location-pin"></use>
          </svg>

          <button className={homeClass["btn-inline"]}>
            Albufeira, Portugal
          </button>
        </div>

        <div className={homeClass["overview__rating"]}>
          <div className={homeClass["overview__rating-average"]}>8.6</div>
          <div className={homeClass["overview__rating-count"]}>478 votes</div>
        </div>
      </div>

      <div className={layoutClass.detail}>
        <div className={layoutClass.description}>
          <div className={homeClass.paragraph}>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Delectus
            vero illum quasi quae? Corporis at dolor natus ratione, dicta,
            praesentium alias odit ad sint, labore corrupti saepe minima
            voluptatibus? Nulla.
          </div>
          <div className={homeClass.paragraph}>
            Corporis at dolor natus ratione, dicta, praesentium alias odit ad
            sint, labore corrupti saepe minima voluptatibus? Nulla.
          </div>
          <ul className={homeClass.list}>
            <li className={homeClass["list__item"]}>Close to the beach</li>
            <li className={homeClass["list__item"]}>Breakfast included</li>
            <li className={homeClass["list__item"]}>Free airport shuttle</li>
            <li className={homeClass["list__item"]}>Free wifi in all rooms</li>
            <li className={homeClass["list__item"]}>
              Air conditioning and heating
            </li>
            <li className={homeClass["list__item"]}>Pets allowed</li>
            <li className={homeClass["list__item"]}>We speak all languages</li>
            <li className={homeClass["list__item"]}>Perfect for families</li>
          </ul>
          <div className={homeClass.recommend}>
            <p className={homeClass["recommend__count"]}>
              Lucy and 3 other friends recommend this hotels
            </p>
            <div className={homeClass["recommend__friends"]}>
              <div className={homeClass["recommend__photo"]}>
                <Image
                  layout="fill"
                  objectFit="contain"
                  src="/img/user-3.jpg"
                  alt="User Photo"
                ></Image>
              </div>
              <div className={homeClass["recommend__photo"]}>
                <Image
                  layout="fill"
                  objectFit="contain"
                  src="/img/user-4.jpg"
                  alt="User Photo"
                ></Image>
              </div>
              <div className={homeClass["recommend__photo"]}>
                <Image
                  layout="fill"
                  objectFit="contain"
                  src="/img/user-5.jpg"
                  alt="User Photo"
                ></Image>
              </div>
              <div className={homeClass["recommend__photo"]}>
                <Image
                  layout="fill"
                  objectFit="contain"
                  src="/img/user-6.jpg"
                  alt="User Photo"
                ></Image>
              </div>
            </div>
          </div>
        </div>
        <div className={layoutClass["user-reviews"]}>
          <figure className={homeClass.review}>
            <blockquote className={homeClass["review__text"]}>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit
              modi itaque amet mollitia velit voluptatibus nobis, repudiandae
              non! Cumque, delectus corporis? Nostrum, illo? Saepe, quam aperiam
              harum excepturi voluptatibus tempora?
            </blockquote>
            <figcaption className={homeClass["review__user"]}>
              <img
                src="/img/user-1.jpg"
                alt="User 1"
                className={homeClass["review__photo"]}
              />
              <div className={homeClass["review__user-box"]}>
                <p className={homeClass["review__user-name"]}>Nick Smith</p>
                <p className={homeClass["review__user-date"]}>Feb 23rd, 2017</p>
              </div>
              <div className={homeClass["review__rating"]}>7.8</div>
            </figcaption>
          </figure>
          <figure className={homeClass.review}>
            <blockquote className={homeClass["review__text"]}>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit
              modi itaque amet mollitia velit voluptatibus nobis, repudiandae
              non! Cumque, delectus corporis? Nostrum, illo? Saepe, quam aperiam
              harum excepturi voluptatibus tempora?
            </blockquote>
            <figcaption className={homeClass["review__user"]}>
              <img
                src="/img/user-2.jpg"
                alt="User 2"
                className={homeClass["review__photo"]}
              />
              <div className={homeClass["review__user-box"]}>
                <p className={homeClass["review__user-name"]}>Mary Smith</p>
                <p className={homeClass["review__user-date"]}>Feb 23rd, 2017</p>
              </div>
              <div className={homeClass["review__rating"]}>7.8</div>
            </figcaption>
          </figure>
          <button className={homeClass["btn-inline"]}>
            Show all <span> &rarr; </span>
          </button>
        </div>

      
      </div>
      <div className={homeClass.cta}>
          <h2 className={homeClass['cta__book-now']}>
            Good news! We have 4 free rooms for your selected dates!
          </h2>
          <button className={homeClass.btn}>
            <span className={homeClass['btn__visible']}> Book now</span>
            <span className={homeClass['btn__invisible']}>Only $ rooms left</span>
            </button>
        </div>
    </div>
  );
}
